<a href="https://colab.research.google.com/github/bbookman/ds-class-exercises/blob/master/BRB_Solutions_Numpy_additional_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Create a numpy array of size 10, filled with zeros.
import numpy as np
a = np.zeros(10, dtype=int)
print(str(a))

[0 0 0 0 0 0 0 0 0 0]


In [7]:
# Create a numpy array with values ranging from 10 to 49
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
# Create a numpy matrix of 2*2 integers, filled with ones
matrix = np.ndarray((2,2), dtype=int)
matrix.fill(1)
print(matrix)

# OR
m_ones = np.ones([2,2], dtype =int)
print(m_ones)

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


In [29]:
#  Create a numpy matrix of 3*2 float numbers, filled with one
c = np.ndarray((3,2), dtype=float)
c.fill(1)
print(c)

# OR
d = np.ones([3,2], dtype=float)
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)
Y = np.zeros_like(X)
print(X)
print(Y)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]
